DROP TABLE IF EXISTS usuarios CASCADE;
DROP TABLE IF EXISTS equipos CASCADE;
DROP TABLE IF EXISTS tipos_in CASCADE;
DROP TABLE IF EXISTS interfaces CASCADE;
DROP TABLE IF EXISTS direcciones_IP CASCADE;
